name: odcey
#base: core18
base: bare
build-base: core22
adopt-info: odcey
license: Apache-2.0
summary: Text converter of ".odc"-format from BlackBox Component Builder
description: |
  Converter to plain text Oberon document binary format,
  used by the BlackBox Component Builder.
  Usable as text converter in .git for readable diffs of odc-documents.

grade: stable
confinement: strict

parts:
  odcey:
    plugin: nil
    build-snaps:
      - vostok/latest/beta
    build-packages:
      - on !i386:
        - musl-tools

    override-build: |
      snap alias vostok ost
      if [ "${SNAPCRAFT_TARGET_ARCH}" = i386 ]; then
        CC="gcc -O2 -flto"
        snapcraftctl set-version $(ost run odcey.Cli -m . -- version)
      else
        CC="musl-gcc -Os -flto=auto -static"
        craftctl set version=$(./odcey.mod Cli version)
      fi
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      ost to-bin odcey.Cli $SNAPCRAFT_PART_INSTALL/usr/bin/odcey -m . -cc "$CC -s"

    source:
      .

apps:
  odcey:
    command: usr/bin/odcey
    plugs:
      - home
